### ISSUE TITLE
Rig kicked off server every time an experiment ends

### ISSUE THREAD

**Issue by laurax452** [cortex-lab/Rigbox#260] opened 2020-02-11 13:57 UTC
Error using jsonencode
Unable to encode objects of class dfilt.df2sos as JSON-formatted text.

Error in obj2json (line 9)
  s = jsonencode(s, 'ConvertInfAndNaN', true);

Error in srv.expServer/runExp (line 311)
    fprintf(fid, '%s', obj2json(rig));

Error in srv.expServer/handleMessage (line 231)
              aborted = runExp(expRef, preDelay, postDelay, AlyxInstance);

Error in srv.expServer (line 128)
    handleMessage(msgid, msgdata, host);

**Comment by k1o0** [comment] 2020-02-11 14:34
Duplicate of  #233

**Closed by k1o0** 2020-02-11 14:34 UTC
Labels: duplicate
